language: python
python: '3.5'
sudo: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
  matrix:
    - TOXENV=check
    - TOXENV=py27-46-028
    - TOXENV=py27-46-029
    - TOXENV=py36-46-028
    - TOXENV=py36-46-029
    - TOXENV=py36-54-028
    - TOXENV=py36-54-029
    - TOXENV=py36-62-028
    - TOXENV=py36-62-029
    - TOXENV=py37-46-028
    - TOXENV=py37-46-029
    - TOXENV=py37-54-028
    - TOXENV=py37-54-029
    - TOXENV=py37-62-028
    - TOXENV=py37-62-029
    - TOXENV=py38-46-029
    - TOXENV=py38-54-029
    - TOXENV=py38-62-029
    - TOXENV=pypy-46-029
    - TOXENV=pypy-54-029
    - TOXENV=pypy-62-029
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email:
    on_success: never
    on_failure: always
